image: Ubuntu
stack: jdk 11
build_script:
- mvn install
cache:
- /home/appveyor/.m2/repository/ -> pom.xml
artifacts:
  - path: target/possibly-1.0.0-SNAPSHOT.jar
    name: Possibly 1.0.0 Snapshot
  - path: target/possibly-1.0.0-SNAPSHOT-sources.jar
    name: Possibly Source 1.0 Snapshot
  - path: target/possibly-1.0.0-SNAPSHOT-javadoc.jar
    name: Possibly JavaDocs 1.0 Snapshot
on_finish:
  - sh: |
      find "$APPVEYOR_BUILD_FOLDER" -type f -name 'TEST*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"
